import Head from "next/head";
import CheckAvailability from "@/components/home_components/check_availability/CheckAvailability";
import ContactDetails from "@/components/home_components/contact_details";
import Booking from "@/components/home_components/booking";
import Footer from "@/components/Footer";
import OurServices from "@/components/home_components/our_services";
import Testimonials from "@/components/home_components/testimonials";
import Image from "next/image";
import styles from "../styles/Home.module.css";




export default function Home() {
  return (
    <>
      <Head>
        <title>SLViking Villa</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div className="container-fluid p-0 m-0">
          {/* hero section */}
          <div className={`hero_comp d-flex flex-column flex-lg-row px-2 px-lg-5 ${styles.heroContainer}`}>

            <div className="col-12 col-lg-6 d-flex d-lg-none justify-content-center align-items-center">
              <Image
                src={"/assests/images/bg/home_bg.png"}
                alt=""
                width={350}
                height={300}
                className="img-fluid mt-5"
              />
            </div>
            <div className="col-12 col-lg-6 px-0 px-md-5 d-flex flex-column justify-content-center align-items-center">
              <h1 className="text-white font-comorant text-center text-lg-start">Welcome to Viking Villa Resturent</h1>
              <p className="text-white font-josefin text-center text-lg-start px-0 px-md-5 px-lg-0">Welcome to a World of Refined Hospitality, Where Unmatched Service Meets Unparalleled Comfort</p>
            </div>
            <div className="col-12 col-lg-6 d-none d-lg-flex justify-content-end position-relative">
              <Image
                src={"/assests/images/bg/home_bg.png"}
                alt=""
                width={450}
                height={400}
                className={`img-fluid ${styles.heroImage}`}
                style={{ zIndex: 1 }}
              />
            </div>
          </div>
          {/* hero section end */}
          <CheckAvailability />
          <ContactDetails />
          {/* the story section */}
          <div className="d-flex px-2 px-lg-5 pb-0 pb-lg-5">
            <div className="d-flex flex-column flex-lg-row px-0 px-lg-5 py-0 py-lg-5">
              <div
                className={`col-12 col-lg-6 d-flex flex-column justify-content-center align-items-center  px-0 px-md-5 ${styles.borderRight}`}
              >
                <Image
                  src={"/assests/images/bg/the_story.png"}
                  alt=""
                  width={350}
                  height={300}
                  className={`${styles.imgStory}`}
                />
              </div>
              <div
                className={`col-12 col-lg-6 d-flex flex-column justify-content-center align-items-center px-0 px-md-5 px-lg-0 ${styles.storySec} px-0 px-lg-5`}
              >
                <div className="d-flex flex-column mb-4 mt-4 mt-lg-0">
                  <h3 className="mb-0">The Story</h3>
                  <p className="mb-0">
                    Embark on a Remarkable Journey of Cultural Fusion and Unmatched
                    Hospitality at the Finest Hotel in Sri Lanka, Owned by a Danish
                    Entrepreneur. Experience the Perfect Blend of Sri Lankan Charm
                    and European Elegance, Where Our Expertise in Hospitality
                    Creates a Sanctuary of Comfort and Freedom. Welcome to the
                    Epitome of Tranquility, the Most Exquisite and Comfortable
                    Destination in Sri Lanka
                  </p>
                </div>
                <div className="d-flex flex-column flex-md-row mb-4">
                  <div className="col-12 col-md-6 d-flex flex-column me-0 me-md-2">
                    <h3 className="mb-0">2016</h3>
                    <p>
                      Where Cultural Fusion Meets Comfort. Welcome to Tranquility,
                      Sri Lanka&apos;s Premier Boutique Hotel.
                    </p>
                    <span className="mb-0">Asoka Premadige</span>
                    <Image
                      src={"/assests/images/bg/signature.png"}
                      alt=""
                      width={100}
                      height={100}
                      className={`img-fluid`}
                    />
                  </div>
                  <div className="col-12 col-md-6 d-flex flex-column ms-0 ms-md-2">
                    <h3 className="mb-0">2023</h3>
                    <p>
                      We proudly celebrate 07 years of dedicated service, adorned
                      with great honor and unwavering commitment
                    </p>
                  </div>
                </div>
              </div>
            </div>
          </div>
          {/* the story section end */}
          {/* plan your tou section */}
          <div className="d-flex flex-column px-0 px-lg-5 pt-5 pb-0 pb-lg-5">
            <div className="d-flex px-0 px-lg-5 pb-0 pb-lg-5">
              <div
                className={`d-flex ${styles.planWrapperImage} position-relative`}
              >
                <div
                  className={`col-12 col-lg-5 px-3 px-md-5 py-5 p-lg-5 d-flex flex-column ${styles.planWrapper} `}
                >
                  <h3>Plan Your Journey</h3>
                  <p>
                    We specialize in helping you plan your trip to Sri Lanka,
                    ensuring an unforgettable experience. Our team will introduce
                    you to the best places, arrange reliable transportation, and
                    make hotel reservations tailored to your preferences. We are
                    dedicated to making your journey comfortable and joyful, so you
                    can relax and fully immerse yourself in the beauty of Sri Lanka.
                  </p>
                  <button
                    className={`${styles.filledBtn} ${styles.btnAll} px-2 py-2`}
                  >
                    Start Plan your Trip
                  </button>
                </div>
              </div>
            </div>
            <div className="d-flex px-0 px-lg-5">
              <div
                className={`d-flex ${styles.tourWrapperImage} position-relative`}
              >
                <div
                  className={`col-12 col-lg-5 px-3 px-md-5 py-5 p-lg-5 d-flex flex-column ${styles.tourWrapper} `}
                >
                  <h3>Plan Your Journey</h3>
                  <p>
                    We specialize in helping you plan your trip to Sri Lanka,
                    ensuring an unforgettable experience. Our team will introduce
                    you to the best places, arrange reliable transportation, and
                    make hotel reservations tailored to your preferences. We are
                    dedicated to making your journey comfortable and joyful, so you
                    can relax and fully immerse yourself in the beauty of Sri Lanka.
                  </p>
                  <div className="d-flex flex-row">
                    <div className="col-2 d-flex align-items-center">
                      <Image
                        src={"/assests/images/icons/Airport.png"}
                        alt=""
                        width={22}
                        height={22}
                        className={`img-fluid`}
                      />
                    </div>
                    <div className="col-7 d-flex align-items-center">
                      <span>AIRPORT</span>
                    </div>
                    <div className="col-3 d-flex align-items-center">
                      <span>35 Min</span>
                    </div>
                  </div>
                  <div className="d-flex flex-row mb-4">
                    <div className="col-2 d-flex align-items-center">
                      <Image
                        src={"/assests/images/icons/Railway Station.png"}
                        alt=""
                        width={22}
                        height={22}
                        className={`img-fluid`}
                      />
                    </div>
                    <div className="col-7 d-flex align-items-center">
                      <span className="mb-0">RAILWAY STATION</span>
                    </div>
                    <div className="col-3 d-flex align-items-center">
                      <span className="mb-0">20 Min</span>
                    </div>
                  </div>
                  <button
                    className={`${styles.filledBtn} ${styles.btnAll} px-2 py-2`}
                  >
                    Read More
                  </button>
                </div>
              </div>
            </div>
          </div>
          {/* plan your tou section end */}
          <Testimonials />
          {/* image section */}
          <div className={`d-flex position-relative px-2 px-lg-5 ${styles.imgGroupWrapper} justify-content-end align-items-center`}>
            <Image
              src={"/assests/images/bg/img_group.png"}
              alt=""
              width={450}
              height={400}
              className={`${styles.imgGroup} px-0 px-lg-5`}
            />
          </div>
          {/* image section */}
          {/* desc 1 */}
          <div className="d-flex flex-column px-2 px-lg-5 py-5">
            <div className="d-flex flex-column flex-lg-row px-0 px-lg-5 pt-5">
              <div className="col-12 col-lg-6 pb-lg-0">
                <Image
                  src={"/assests/images/bg/tour_planing.png"}
                  alt=""
                  width={350}
                  height={300}
                  className={`${styles.imgStory}`}
                />
              </div>
              <div className={`col-12 col-lg-6 py-5 ps-0 ps-lg-5 d-flex flex-column justify-content-center ${styles.Descrioption}`}>
                <h3 className="d-flex flex-column">
                  Tour Planning
                </h3>
                <p className="mb-0">
                  Based on your budget, we specialize in crafting personalized itineraries with incredible amenities. Our team has meticulously designed route plans with superlative facilities, accompanied by detailed maps for your convenience. You also have the freedom to choose specific destinations and collaborate with us to create a tailored plan that suits your preferences. With our unwavering commitment to excellence, we provide the finest services to ensure your journey is truly remarkable
                </p>
              </div>
            </div>
            <div className="d-flex flex-column flex-lg-row-reverse px-0 px-lg-5 pb-5">
              <div className="col-12 col-lg-6  pt-lg-0">
                <Image
                  src={"/assests/images/bg/hire_vehicle.png"}
                  alt=""
                  width={350}
                  height={300}
                  className={`${styles.imgStory}`}
                />
              </div>
              <div className={`col-12 col-lg-6 py-5 ps-0 pe-lg-5 d-flex flex-column justify-content-center ${styles.Descrioption}`}>
                <h3 className="d-flex flex-column">
                  Hire Vehicle
                </h3>
                <p className="mb-0">
                  We offer a wide range of comfortable vehicles at affordable prices, ensuring the perfect transportation solution for your needs. Our fleet comprises top-quality vehicles that prioritize your comfort and safety. Experience a seamless travel experience with our reliable and well-maintained vehicles, tailored to provide the utmost convenience during your trip. Enjoy the peace of mind knowing that you have the best transportation at a reasonable price.
                </p>
              </div>
            </div>
          </div>
          {/* desc 1 end */}
          <OurServices />
          {/* desc 2 */}
          <div className="d-flex flex-column px-2 px-lg-5 py-5">
            <div className="d-flex flex-column flex-lg-row px-0 px-lg-5 pt-0 pt-lg-5">
              <div className="col-12 col-lg-6 pb-lg-0">
                <Image
                  src={"/assests/images/bg/luxury_rooms.png"}
                  alt=""
                  width={350}
                  height={300}
                  className={`${styles.imgStory}`}
                />
              </div>
              <div className={`col-12 col-lg-6 py-5 ps-0 ps-lg-5 d-flex flex-column justify-content-center ${styles.Descrioption}`}>
                <h3 className="d-flex flex-column">
                  Luxury Rooms
                </h3>
                <p className="mb-0">
                  Unleash your senses with our restaurant&apos;s luxurious rooms. Immerse yourself in opulence, where elegance meets comfort. Experience the epitome of luxury, right within our doors.
                </p>
              </div>
            </div>
            <div className="d-flex flex-column flex-lg-row-reverse px-0 px-lg-5 pb-0 pb-lg-5">
              <div className="col-12 col-lg-6  pt-lg-0">
                <Image
                  src={"/assests/images/bg/cultural_foods.png"}
                  alt=""
                  width={350}
                  height={300}
                  className={`${styles.imgStory}`}
                />
              </div>
              <div className={`col-12 col-lg-6 py-5 ps-0 pe-lg-5 d-flex flex-column justify-content-center ${styles.Descrioption}`}>
                <h3 className="d-flex flex-column">
                  Cultural Foods
                </h3>
                <p className="mb-0">
                  Experience the captivating flavors of Sri Lanka with our authentic cultural foods. Indulge in a culinary adventure as we bring the vibrant spices and traditional dishes of Sri Lanka to your plate. Immerse yourself in a fusion of tastes and aromas that will transport you to the heart of this enchanting island.
                </p>
              </div>
            </div>
          </div>
          {/* desc 2 end */}
          <Booking />
        </div>
      </main>
    </>
  );
}
